plugins { id 'com.android.application' }

android { namespace 'com.thor.bypasscharging'; compileSdk 37
    defaultConfig { applicationId 'com.thor.bypasscharging'; minSdk 29; targetSdk 37; versionCode 2; versionName '2.0.0' }
    buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
}
